[package]
name = "rtorrent-remote"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
magnet-url = "2.0.0"
curl = "0.4.39"
url = "2.2"